import { FormEvent, useEffect, useState } from "react";
import { assignStaffTicket, claimStaffTicket, createInternalNote, createStaffComment, downloadStaffAttachment, fetchStaffTicketDetail, InternalNote, StaffTicketDetail as StaffTicketDetailData, TicketPriority, TicketStatus, updateStaffTicketPriority, updateStaffTicketStatus } from "./api.js";

const statuses: TicketStatus[] = ["NEW", "OPEN", "IN_PROGRESS", "WAITING_FOR_REQUESTER", "RESOLVED", "CLOSED", "REOPENED", "CANCELLED"];
const priorities: TicketPriority[] = ["LOW", "MEDIUM", "HIGH", "URGENT"];

export default function StaffTicketDetail({ ticketId, onBack }: { ticketId: number; onBack: () => void }) {
  const [ticket, setTicket] = useState<StaffTicketDetailData | null>(null);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const [error, setError] = useState("");
  const [operationError, setOperationError] = useState("");
  const [busy, setBusy] = useState(false);
  const [ownerId, setOwnerId] = useState("");
  const [priority, setPriority] = useState<TicketPriority | "">("");
  const [nextStatus, setNextStatus] = useState<TicketStatus | "">("");
  const [confirmation, setConfirmation] = useState(false);
  const [reason, setReason] = useState("");
  const [publicComment, setPublicComment] = useState("");
  const [internalNote, setInternalNote] = useState("");

  async function load() {
    setState("loading"); setError("");
    try { const value = await fetchStaffTicketDetail(ticketId); setTicket(value); setOwnerId(value.owner ? String(value.owner.id) : ""); setPriority(value.itPriority ?? ""); setState("ready"); } catch (reasonValue) { setError(reasonValue instanceof Error ? reasonValue.message : "Ticket not found or unavailable"); setState("error"); }
  }
  useEffect(() => { void load(); }, [ticketId]);

  async function run(operation: () => Promise<void>) { setBusy(true); setOperationError(""); try { await operation(); await load(); } catch (reasonValue) { setOperationError(reasonValue instanceof Error ? reasonValue.message : "Unable to save Ticket changes"); } finally { setBusy(false); } }
  async function submitAssignment(event: FormEvent) { event.preventDefault(); if (!ownerId.trim() || !/^\d+$/.test(ownerId.trim())) { setOperationError("Owner User ID must be a positive numeric ID"); return; } await run(() => assignStaffTicket(ticketId, Number(ownerId))); }
  async function submitStatus(event: FormEvent) { event.preventDefault(); if (!nextStatus) { setOperationError("Choose a next status"); return; } await run(() => updateStaffTicketStatus(ticketId, nextStatus, { confirmation, reason: reason.trim() })); setNextStatus(""); setConfirmation(false); setReason(""); }
  async function submitPublicComment(event: FormEvent) { event.preventDefault(); if (!publicComment.trim()) { setOperationError("Public Comment cannot be blank"); return; } await run(async () => { await createStaffComment(ticketId, publicComment); setPublicComment(""); }); }
  async function submitInternalNote(event: FormEvent) { event.preventDefault(); if (!internalNote.trim()) { setOperationError("Internal Note cannot be blank"); return; } await run(async () => { await createInternalNote(ticketId, internalNote); setInternalNote(""); }); }

  if (state === "loading") return <section className="ticket-detail" aria-labelledby="staff-ticket-detail-heading"><h2 id="staff-ticket-detail-heading">Staff Ticket Detail</h2><div className="state-callout state-info" role="status">Loading Staff Ticket...</div></section>;
  if (state === "error" || !ticket) return <section className="ticket-detail" aria-labelledby="staff-ticket-detail-heading"><h2 id="staff-ticket-detail-heading">Staff Ticket Detail</h2><div className="state-callout state-error" role="alert"><strong>{error || "Ticket not found or unavailable."}</strong><p>Operational Ticket details are available only to IT Staff and Administrators.</p><button className="retry-button" type="button" onClick={() => void load()}>Retry</button></div><button className="btn btn-secondary-green" type="button" onClick={onBack}>Back to Queue</button></section>;

  return <section className="ticket-detail staff-ticket-detail" aria-labelledby="staff-ticket-detail-heading">
    <div className="list-header"><div><p className="eyebrow">Operational Staff workspace</p><h2 id="staff-ticket-detail-heading">{ticket.ticketNumber}</h2><p className="helper-text">Last updated {new Date(ticket.updatedAt).toLocaleString()}</p></div><button className="btn btn-secondary-green" type="button" onClick={onBack}>Back to Queue</button></div>
    {operationError && <div className="state-callout state-error" role="alert">{operationError}</div>}
    <div className="detail-grid"><div><dt>Status</dt><dd><span className="status-badge">{ticket.currentStatus}</span></dd></div><div><dt>Requested Priority</dt><dd><span className="status-badge">{ticket.requestedPriority}</span></dd></div><div><dt>IT Priority</dt><dd><span className="status-badge">{ticket.itPriority ?? "UNASSIGNED"}</span></dd></div><div><dt>Owner</dt><dd>{ticket.owner ? `${ticket.owner.name} (${ticket.owner.role})` : "Unassigned"}</dd></div><div><dt>Requester</dt><dd>{ticket.requester.name} ({ticket.requester.email})</dd></div><div><dt>Requester Resolution</dt><dd>{ticket.requesterConfirmedResolved ? "Requester indicated resolved" : "No indication"}</dd></div><div><dt>Category</dt><dd>{ticket.category.name}</dd></div><div><dt>Related System</dt><dd>{ticket.relatedSystem.name}</dd></div><div><dt>Created</dt><dd>{new Date(ticket.createdAt).toLocaleString()}</dd></div></div>
    <div className="detail-section"><h3>{ticket.summary}</h3><p className="staff-description">{ticket.description}</p></div>
    <section className="operational-controls" aria-labelledby="operational-controls-heading"><h3 id="operational-controls-heading">Operational Controls</h3><div className="control-grid">
      <div className="control-card"><h4>Ownership</h4>{!ticket.owner && <button className="btn btn-primary-green" type="button" disabled={busy} onClick={() => void run(() => claimStaffTicket(ticketId))}>Claim for me</button>}{ticket.owner && <><form onSubmit={submitAssignment}><label htmlFor="staff-owner-id">Assign to active Staff/Admin User ID</label><input id="staff-owner-id" inputMode="numeric" value={ownerId} onChange={(event) => setOwnerId(event.target.value)} /><button className="btn btn-secondary-green" type="submit" disabled={busy}>Reassign Owner</button></form><button className="btn btn-secondary-green" type="button" disabled={busy || !["NEW", "OPEN"].includes(ticket.currentStatus)} onClick={() => void run(() => assignStaffTicket(ticketId, null))}>Unassign</button><p className="helper-text">Unassignment is available only while the Ticket is New or Open.</p></>}</div>
      <div className="control-card"><h4>IT Priority</h4><label htmlFor="staff-it-priority-detail">Set IT Priority</label><select id="staff-it-priority-detail" value={priority} onChange={(event) => setPriority(event.target.value as TicketPriority | "")}><option value="">Choose a priority</option>{priorities.map((value) => <option key={value} value={value}>{value}</option>)}</select><button className="btn btn-secondary-green" type="button" disabled={busy || !priority} onClick={() => priority && void run(() => updateStaffTicketPriority(ticketId, priority))}>Save IT Priority</button></div>
      <div className="control-card"><h4>Status Transition</h4><form onSubmit={submitStatus}><label htmlFor="staff-next-status">Next status</label><select id="staff-next-status" value={nextStatus} onChange={(event) => setNextStatus(event.target.value as TicketStatus | "")}><option value="">Choose a next status</option>{statuses.filter((value) => value !== ticket.currentStatus).map((value) => <option key={value} value={value}>{value}</option>)}</select><label htmlFor="staff-status-reason">Reason (required for Cancelled/Reopened)</label><textarea id="staff-status-reason" value={reason} onChange={(event) => setReason(event.target.value)} maxLength={2000} /><label className="checkbox-label"><input type="checkbox" checked={confirmation} onChange={(event) => setConfirmation(event.target.checked)} /> I confirm this status transition</label><button className="btn btn-primary-green" type="submit" disabled={busy || !nextStatus}>Update Status</button></form></div>
    </div></section>
    <div className="detail-section"><h3>Attachments <span className="private-badge">Read/download only</span></h3>{ticket.attachments.length === 0 ? <p className="helper-text">No attachments.</p> : <ul>{ticket.attachments.map((file) => <li key={file.id}>{file.removedAt ? <s>{file.originalName}</s> : <button className="btn btn-secondary-green" type="button" onClick={() => void downloadStaffAttachment(ticket.id, file.id, file.originalName)}>{file.originalName}</button>} ({file.mimeType}, {file.sizeBytes} bytes){file.removedAt && <span> — Removed: {file.removedReason}</span>}</li>)}</ul>}</div>
    <div className="detail-section public-comments"><h3>Public Comments <span className="public-badge">Requester-visible</span></h3>{ticket.publicComments.length === 0 ? <p className="helper-text">No public comments yet.</p> : <ul>{ticket.publicComments.map((entry) => <li key={entry.id}><strong>{entry.author.name}</strong> <span className="helper-text">({new Date(entry.createdAt).toLocaleString()})</span><p>{entry.body}</p></li>)}</ul>}<form onSubmit={submitPublicComment}><label htmlFor="staff-public-comment">Add public comment</label><textarea id="staff-public-comment" value={publicComment} onChange={(event) => setPublicComment(event.target.value)} maxLength={2000} /><button className="btn btn-secondary-green" type="submit" disabled={busy}>{busy ? "Saving..." : "Add Public Comment"}</button></form></div>
    <div className="detail-section internal-notes"><h3>Internal Notes <span className="private-badge">Staff/Admin only</span></h3>{ticket.internalNotes.length === 0 ? <p className="helper-text">No internal notes yet.</p> : <ul>{ticket.internalNotes.map((entry: InternalNote) => <li key={entry.id}><strong>{entry.author.name}</strong> <span className="helper-text">({new Date(entry.createdAt).toLocaleString()})</span><p>{entry.body}</p></li>)}</ul>}<form onSubmit={submitInternalNote}><label htmlFor="staff-internal-note">Add internal note</label><textarea id="staff-internal-note" value={internalNote} onChange={(event) => setInternalNote(event.target.value)} maxLength={4000} /><button className="btn btn-secondary-green" type="submit" disabled={busy}>{busy ? "Saving..." : "Add Internal Note"}</button></form></div>
  </section>;
}
