import { useEffect, useState } from "react";
import { downloadAttachment, fetchTicketDetail, removeAttachment, TicketDetail as TicketDetailData, uploadAttachments } from "./api.js";

export default function TicketDetail({ requesterId, ticketId, onBack }: { requesterId: number; ticketId: number; onBack: () => void }) {
  const [ticket, setTicket] = useState<TicketDetailData | null>(null);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const [uploadError, setUploadError] = useState("");
  useEffect(() => { setState("loading"); void fetchTicketDetail(requesterId, ticketId).then((value) => { setTicket(value); setState("ready"); }).catch(() => setState("error")); }, [requesterId, ticketId]);
  if (state === "loading") return <section className="ticket-detail" aria-labelledby="ticket-detail-heading"><h2 id="ticket-detail-heading">Ticket Detail</h2><div className="state-callout state-info" role="status">Loading Ticket...</div></section>;
  if (state === "error" || !ticket) return <section className="ticket-detail" aria-labelledby="ticket-detail-heading"><h2 id="ticket-detail-heading">Ticket Detail</h2><div className="state-callout state-error" role="alert"><strong>Ticket not found or unavailable.</strong><p>You can only view tickets owned by the current Requester.</p></div><button className="btn btn-secondary-green" type="button" onClick={onBack}>Back to My Tickets</button></section>;
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const files = Array.from(event.target.files ?? []); if (!files.length) return; setUploadError(""); try { await uploadAttachments(requesterId, ticketId, files); setTicket(await fetchTicketDetail(requesterId, ticketId)); } catch (error) { setUploadError(error instanceof Error ? error.message : "Unable to upload attachments"); } event.target.value = ""; }
  return <section className="ticket-detail" aria-labelledby="ticket-detail-heading"><div className="list-header"><div><p className="eyebrow">Ticket workspace</p><h2 id="ticket-detail-heading">{ticket.ticketNumber}</h2></div><button className="btn btn-secondary-green" type="button" onClick={onBack}>Back to My Tickets</button></div><div className="detail-grid"><div><dt>Status</dt><dd><span className="status-badge">{ticket.currentStatus}</span></dd></div><div><dt>Requested Priority</dt><dd>{ticket.requestedPriority}</dd></div><div><dt>Requester</dt><dd>{ticket.requester.name} ({ticket.requester.email})</dd></div><div><dt>Category</dt><dd>{ticket.category.name}</dd></div><div><dt>Related System</dt><dd>{ticket.relatedSystem.name}</dd></div><div><dt>Created</dt><dd>{new Date(ticket.createdAt).toLocaleString()}</dd></div></div><div className="detail-section"><h3>{ticket.summary}</h3><p>{ticket.description}</p></div><div className="detail-section"><h3>Attachments</h3><label htmlFor="attachment-upload">Add attachments</label><input id="attachment-upload" type="file" multiple accept=".jpg,.jpeg,.png,.webp,.pdf" onChange={upload} />{uploadError && <p className="state-callout state-error" role="alert">{uploadError}</p>}{ticket.attachments.length === 0 ? <p className="helper-text">No attachments.</p> : <ul>{ticket.attachments.map((file) => <li key={file.id}>{file.removedAt ? <s>{file.originalName}</s> : <button className="btn btn-secondary-green" type="button" onClick={() => void downloadAttachment(requesterId, ticket.id, file.id, file.originalName)}>{file.originalName}</button>} ({file.mimeType}, {file.sizeBytes} bytes){file.removedAt ? <span> — Removed: {file.removedReason}</span> : <button className="btn btn-secondary-green" type="button" onClick={async () => { const reason = window.prompt("Removal reason"); if (reason) { await removeAttachment(requesterId, ticket.id, file.id, reason); setTicket(await fetchTicketDetail(requesterId, ticket.id)); } }}>Remove</button>}</li>)}</ul>}</div></section>;
}
