import { useEffect, useState } from "react";
import { fetchTicketDetail, TicketDetail as TicketDetailData } from "./api.js";

export default function TicketDetail({ requesterId, ticketId, onBack }: { requesterId: number; ticketId: number; onBack: () => void }) {
  const [ticket, setTicket] = useState<TicketDetailData | null>(null);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  useEffect(() => { setState("loading"); void fetchTicketDetail(requesterId, ticketId).then((value) => { setTicket(value); setState("ready"); }).catch(() => setState("error")); }, [requesterId, ticketId]);
  if (state === "loading") return <section className="ticket-detail" aria-labelledby="ticket-detail-heading"><h2 id="ticket-detail-heading">Ticket Detail</h2><div className="state-callout state-info" role="status">Loading Ticket...</div></section>;
  if (state === "error" || !ticket) return <section className="ticket-detail" aria-labelledby="ticket-detail-heading"><h2 id="ticket-detail-heading">Ticket Detail</h2><div className="state-callout state-error" role="alert"><strong>Ticket not found or unavailable.</strong><p>You can only view tickets owned by the current Requester.</p></div><button className="btn btn-secondary-green" type="button" onClick={onBack}>Back to My Tickets</button></section>;
  return <section className="ticket-detail" aria-labelledby="ticket-detail-heading"><div className="list-header"><div><p className="eyebrow">Read-only view</p><h2 id="ticket-detail-heading">{ticket.ticketNumber}</h2></div><button className="btn btn-secondary-green" type="button" onClick={onBack}>Back to My Tickets</button></div><div className="detail-grid"><div><dt>Status</dt><dd><span className="status-badge">{ticket.currentStatus}</span></dd></div><div><dt>Requested Priority</dt><dd>{ticket.requestedPriority}</dd></div><div><dt>Requester</dt><dd>{ticket.requester.name} ({ticket.requester.email})</dd></div><div><dt>Category</dt><dd>{ticket.category.name}</dd></div><div><dt>Related System</dt><dd>{ticket.relatedSystem.name}</dd></div><div><dt>Created</dt><dd>{new Date(ticket.createdAt).toLocaleString()}</dd></div></div><div className="detail-section"><h3>{ticket.summary}</h3><p>{ticket.description}</p></div><div className="detail-section"><h3>Attachments</h3>{ticket.attachments.length === 0 ? <p className="helper-text">No attachments.</p> : <ul>{ticket.attachments.map((file) => <li key={file.id}>{file.originalName} ({file.mimeType}, {file.sizeBytes} bytes)</li>)}</ul>}</div></section>;
}
